// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq50zu9rc9YDMemfXP8NWpDsOPhWulduk',
    appId: '1:963413753770:web:8c200eb1afaf5c1ffef5d3',
    messagingSenderId: '963413753770',
    projectId: 'treasure-hunt-app-5dfbf',
    authDomain: 'treasure-hunt-app-5dfbf.firebaseapp.com',
    storageBucket: 'treasure-hunt-app-5dfbf.firebasestorage.app',
    measurementId: 'G-R156EYRYPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy34I5zJXMh-m1mrnR7hpNvsmMessW24E',
    appId: '1:963413753770:android:088d86b72be8b42cfef5d3',
    messagingSenderId: '963413753770',
    projectId: 'treasure-hunt-app-5dfbf',
    storageBucket: 'treasure-hunt-app-5dfbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz3koud3b7sD-MC6Sa7ClzaPm6-AdoclY',
    appId: '1:963413753770:ios:1c56d36528ebe7ccfef5d3',
    messagingSenderId: '963413753770',
    projectId: 'treasure-hunt-app-5dfbf',
    storageBucket: 'treasure-hunt-app-5dfbf.firebasestorage.app',
    iosBundleId: 'com.example.treasureHuntApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz3koud3b7sD-MC6Sa7ClzaPm6-AdoclY',
    appId: '1:963413753770:ios:1c56d36528ebe7ccfef5d3',
    messagingSenderId: '963413753770',
    projectId: 'treasure-hunt-app-5dfbf',
    storageBucket: 'treasure-hunt-app-5dfbf.firebasestorage.app',
    iosBundleId: 'com.example.treasureHuntApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq50zu9rc9YDMemfXP8NWpDsOPhWulduk',
    appId: '1:963413753770:web:de3dc43e0209ad8cfef5d3',
    messagingSenderId: '963413753770',
    projectId: 'treasure-hunt-app-5dfbf',
    authDomain: 'treasure-hunt-app-5dfbf.firebaseapp.com',
    storageBucket: 'treasure-hunt-app-5dfbf.firebasestorage.app',
    measurementId: 'G-PTTGRS1YK1',
  );
}
